// File generated by FlutterFire CLI.
// This file contains platform-specific Firebase configuration used by
// `Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform)`.
// If you switch Firebase projects, re-run `flutterfire configure`.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// NOTE: This file must match the active Firebase project.
/// If you switch Firebase projects, re-run `flutterfire configure`
/// and select the new project to regenerate this file.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmBaj1OyqdWZhppuL2cN_IcPGx7w8D9JU',
    appId: '1:261489663966:web:7f01f0a734a3856c2b074f',
    messagingSenderId: '261489663966',
    projectId: 'aether-base-b702c',
    authDomain: 'aether-base-b702c.firebaseapp.com',
    storageBucket: 'aether-base-b702c.firebasestorage.app',
    measurementId: 'G-NT18H240XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuS2amdBnl2BWRxjUi5WHIZh6JErucP1U',
    appId: '1:261489663966:android:8d1b3a130cc7f6272b074f',
    messagingSenderId: '261489663966',
    projectId: 'aether-base-b702c',
    storageBucket: 'aether-base-b702c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiB9YzcPnTGlCQw__vKBhGGt9G0KZq_Is',
    appId: '1:261489663966:ios:398d6700d6e96cf92b074f',
    messagingSenderId: '261489663966',
    projectId: 'aether-base-b702c',
    storageBucket: 'aether-base-b702c.firebasestorage.app',
    iosBundleId: 'com.example.aether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiB9YzcPnTGlCQw__vKBhGGt9G0KZq_Is',
    appId: '1:261489663966:ios:398d6700d6e96cf92b074f',
    messagingSenderId: '261489663966',
    projectId: 'aether-base-b702c',
    storageBucket: 'aether-base-b702c.firebasestorage.app',
    iosBundleId: 'com.example.aether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmBaj1OyqdWZhppuL2cN_IcPGx7w8D9JU',
    appId: '1:261489663966:web:239a34fc7bd26e712b074f',
    messagingSenderId: '261489663966',
    projectId: 'aether-base-b702c',
    authDomain: 'aether-base-b702c.firebaseapp.com',
    storageBucket: 'aether-base-b702c.firebasestorage.app',
    measurementId: 'G-9K3B8CHFZX',
  );

}