import 'dart:ui' show ImageFilter, PointerDeviceKind;
import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'journal_test_screen.dart';
import 'report_screen.dart';
import 'test_experience_screen.dart';
import 'dream_entry_screen.dart';
import 'support_wall_screen.dart';
import 'fact_reels_screen.dart';
import 'login_screen.dart';
import 'profile_screen.dart';
import 'notification_screen.dart';
import 'emotional_analytics_screen.dart';
import 'psychiatrist_directory_screen.dart';
import '../services/report_controller.dart';
import '../services/onboarding_service.dart';
import '../widgets/auth_flow_loader.dart';
import '../app_theme.dart';
import 'package:audioplayers/audioplayers.dart';
